### ISSUE TITLE
Preload Trello Board ID

### ISSUE THREAD

**Issue by Prakort** [HarshdipD/eztrackr#52]
**Is your feature request related to a problem? Please describe.**
Instead of asking the user to input the board ID, preload the list of the Trello boards for the user to select. This saves the user time from going back and forth to the Trello board to get the ID.

**Describe the solution you'd like**
List the board ID

**Comment by HarshdipD** [comment]
Good idea. I tried doing this in the first version, but the API does not provide an endpoint to give a list of boards as such, or I couldn't find one at least. If you can that'd be very helpful!
