### ISSUE TITLE
Board ID isn't being saved when using dropdown

### ISSUE THREAD

**Issue by HarshdipD** [HarshdipD/eztrackr#55]
**Describe the bug**
Board ID isn't being saved in local storage when a user uses a dropdown to select their board. This is because the local storage is only being used in the extract function.
![image](https://user-images.githubusercontent.com/31940194/101472695-264b7b00-3906-11eb-8994-a8c025094e42.png)

**To Reproduce**
1. Use the dropdown to select a board
2. When a card is saved, the link goes to Trello homepage instead of the saved board URL - because it doesn't exist on local storage

**Important:**
This needs to be further fixed. We now need a function so that existing users who already have set up a board need to get it saved in on local storage. This would be an enhancement for existing users. Probably an additional API call. Seems useless, but still would be cool to have. We can however skip this for now, and use this API call when we add a new feature - to let users change their board once it has been set.

**Comment by HarshdipD** [comment]
@Prakort

**Comment by Prakort** [comment]
@HarshdipD I had the same idea 👍

**Comment by OmarMorales71** [comment]
@HarshdipD Can I work on this issue?

**Comment by HarshdipD** [comment]
@OmarMorales71 go ahead!

**Comment by HarshdipD** [comment]
Fixed in #63
